my_dict/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('frontend.urls')),
    url(r'', include('lessons.urls')),
    url(r'', include('words.urls')),
    url(r'', include('homework.urls')),
    url(r'^admin/', admin.site.urls),
]

words/urls.py
from django.conf.urls import url, include

from . import views
from knox import views as knox_views
from homework.api import views as homework_views

urlpatterns = [
    url(r'^api/word/translate/(?P<word>[-\'\w() ]+)$', views.WordSingleCreateTranslate.as_view(), name='word-translate'),
    url(r'^api/word/pronounce/(?P<word>[-\'\w() ]+)$', views.WordSingleCreatePronounce.as_view(), name='word-pronounce'),
    url(r'^api/word/conjugate/(?P<word>[-\'\w() ]+)$', views.WordSingleCreateConjugate.as_view(), name='word-conjugate'),
    url(r'^api/word/inflection/(?P<word>[-\'\w() ]+)$', views.WordSingleCreateInflection.as_view(), name='word-inflection'),
    url(r'^api/word/corpora/(?P<word>[-\'\w() ]+)/(?P<ids>[0-9,]+)?$', views.WordExampleSingleDetail.as_view(), name='word-corpora'),
    url(r'^api/word/synonyms/(?P<word>[-\'\w() ]+)$', views.WordSingleCreateSynonyms.as_view(), name='word-synonyms'),
    url(r'^api/word/collocations/(?P<word>[-\'\w() ]+)$', views.WordSingleCreateCollocations.as_view(), name='word-collocations'),

    url(r'^api/word/note/post/$', views.WordNoteSingleCreate.as_view(), name='word-note-post'),
    url(r'^api/word/note/(?P<word>[-\'\w() ]+)/(?P<uuid>[0-9a-f-]+)$', views.WordNoteSingleDetail.as_view(), name='word-note'),

    url(r'^api/word/(?P<word>[-\'\w() ]+)/(?P<uuid>[0-9a-f-]+)?$', views.WordSingleCreate.as_view(), name='word-detail'),
    url(r'^api/word/delete/(?:(?P<word>[-\'\w() ]+)/(?P<uuid>[0-9a-f-]+)/(?P<page>[0-9]+)/(?P<time>[0-9]+)?)?$', views.WordSingleDelete.as_view(), name='word-delete'),
    url(r'^api/words/(?:(?P<uuid>[0-9a-f-]+)/(?P<page>[0-9]+)/(?P<time>[0-9]+)?)?$', views.WordList.as_view(), name='words'),


    url(r'^api/collection/$', views.CollectionListCreate.as_view(), name='save-collection'),
    url(r'^api/collection/(?P<uuid>[0-9a-f-]+)/(?:/(?P<time>[0-9]+))?$', views.CollectionDetail.as_view(), name='collection-detail'),
    url(r'^api/collection/lastmodified/(?P<uuid>[0-9a-f-]+)/(?P<time>[0-9]+)/$', views.CollectionModified.as_view(), name='collection-last-modified'),

    url("^api/auth/register/$", views.RegistrationAPI.as_view()),
    url("^api/auth/login/$", views.LoginAPI.as_view(), name='words_login'),
    url(r'^api/auth/logout/$', knox_views.LogoutView.as_view(), name='knox_logout'),
    url(r'api/auth/logoutall/', knox_views.LogoutAllView.as_view(), name='knox_logoutall'),
    url("^api/auth/user/$", views.UserAPI.as_view()),
    url(r'^api/auth/', include('knox.urls')),

    url(r'^api/book/(?P<what>[-\'\w() ]+)/(?P<page>[0-9]+)$', views.PageCreate.as_view(), name='page-create'),
]

words/models.py
from django.db import models
from django.contrib.auth.models import User
from sortedm2m.fields import SortedManyToManyField
import uuid as uuid_lib
from django.db.models import Case, When, Value, IntegerField, CharField
from django.db.models import Q
from .api_call_helpers import try_fetch
import os
import re
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist 
from bs4 import BeautifulSoup
from .soup_helpers import (scrape_wordref_words, 
                           parse_synonyms,
                           parse_pronounce,
                           parse_straight_word, 
                           parse_reverse_word, 
                           parse_straight_translations, parse_reverse_translations,
                           parse_straight_collocations, parse_reverse_collocations)
from .words_helpers import prep_def_exmpl
from .constants import WORDREF_BASE, OXFORD_BASE

class Etymology(models.Model):
    etymology = models.CharField(max_length=800, null=True)
    word = models.ForeignKey('Word', on_delete=models.CASCADE, related_name='word_etymologies', null=True)
    def __str__(self):
        return self.etymology

    def __unicode__(self):
        return self.etymology

class Collocation(models.Model):
    expression = models.CharField(max_length=800, null=True)
    translation = models.CharField(max_length=800, null=True)
    word = models.ForeignKey('Word', on_delete=models.CASCADE, related_name='word_collocations')
    example = models.CharField(max_length=800, null=True)

    def __str__(self):
        return self.expression

class Definition(models.Model):
    definition = models.TextField(null=True)
    word = models.ForeignKey('Word', on_delete=models.CASCADE, related_name='word_definitions')
    etymology = models.ForeignKey(Etymology, on_delete=models.CASCADE, related_name='definitions', null=True)

    def __str__(self):
        return self.definition

class Example(models.Model):
    example = models.CharField(max_length=800)
    definition = models.ForeignKey(Definition, on_delete=models.CASCADE, related_name='examples', blank=True, null=True)
    word = models.ForeignKey('Word', on_delete=models.CASCADE, related_name='word_examples')

    def __str__(self):
        return self.example

class YandexWordMixin(models.Manager):

  def create_or_get_translations(self, orig_word, **args):
    translations = []

    lang = args['ya_lang']
    language = args['language']

    base_url = 'https://dictionary.yandex.net/api/v1/dicservice.json/lookup'
    params = {
              'key': os.environ.get('YANDEX_API_KEY'),
              'lang': lang,
              'text': orig_word.word,
             }
    
    r = try_fetch(base_url, params=params)
    t = [ d['tr'] for d in r.json()['def'] ]
    words = []
    collocations = {}
    synonyms = {}
    for t in t:
      for t in t:
        word, syn, ex = [ t.get(i) for i in [ 'text', 'syn', 'ex' ] ]
        words.append(word)
        coll_items = []
        word_syns = []
        if syn:
          for s in syn:
            word_syns.append(s['text'])
          synonyms[word] = word_syns
        if ex:
          for t in ex:
            text = t['text']
            trans = ' ,'.join([ i['text'] for i in t['tr'] ])
            coll_items.append({ text: trans })
          collocations[word] = coll_items

    for new_trans in words:
      w = Word.objects.filter(word=new_trans, language=language).first()
      if not w:
        w = Word.objects.create(word=new_trans, lookup_date=timezone.now(), language=language, from_translation=True) 
      w.translations.add(orig_word)
      translations.append(w)
      if synonyms and synonyms.get(new_trans):
        for new_syn in synonyms.get(new_trans):
          s = Word.objects.filter(word=new_syn, language=language).first()
          if not s:
            s = Word.objects.create(word=new_syn, lookup_date=timezone.now(), language=language, from_translation=True) 
          s.synonyms.add(w)

      if collocations and collocations.get(new_trans):
        for expr_trans in collocations.get(new_trans):
          expr_trans = list(*expr_trans.items())
          expr = expr_trans[1]
          trans = expr_trans[0]
          c = Collocation.objects.filter(expression=expr).first()
          if not c:
            print('I am creating some collocations')
            c = Collocation.objects.create(word=w, 
                                           expression=expr, 
                                           translation=trans, 
                                          ) 
    return translations

  def create_or_get_word(self, **args):
    orig_word = args['word']
    lang = args['ya_lang']
    language = args['language']
    
    base_url = 'https://dictionary.yandex.net/api/v1/dicservice.json/lookup'
    params = {
              'key': os.environ.get('YANDEX_API_KEY'),
              'lang': lang,
              'text': orig_word,
             }
    
    r = try_fetch(base_url, params=params)

    t = [ d['tr'] for d in r.json()['def'] ]
    words = []
    examples = {}
    for t in t:
      for t in t:
        word, syn, ex, mean = [ t.get(i) for i in ['text', 'syn', 'ex', 'mean'] ]
        words.append(word)
        ex_items = []
        if ex:
          for t in ex:
            text = t['text']
            trans = ' ,'.join([ i['text'] for i in t['tr'] ])
            ex_items.append(text + ' (' + trans + ')')
          examples[word] = ex_items
        else:
          examples[word] = []
    return self.create_word(language=language, words_map=examples, word=orig_word)

  def create_word(self, **args):
    word = args['word']
    language = args['language']
    words_map = args['words_map']
    if not words_map:
      return ()
    w = Word.objects.filter(word=word, language=language).first()
    if not w:
      w = Word.objects.create(word=word, lookup_date=timezone.now(), language=language)
    else:
      w.from_translation = False
      w.save(update_fields=['from_translation'])
    ety = Etymology.objects.create(word=w, etymology='');

    for definition, examples in words_map.items():
       
      d = Definition.objects.filter(definition=definition, word=w).first()
      if not d:
        d = Definition.objects.create(word=w, definition=definition, etymology=ety);
      if examples:
        [ Example.objects.create(definition=d, example=e, word=w) for e in examples ]
    return (w,)

class LatinWordManager(models.Manager):
  def get_queryset(self):
    return super().get_queryset().filter(language='latin')

  def fetch_translation(self, orig_word):
    trans_to_return = []
    translations_for_db = []
    print('Fetching translations for latin word')
    base_url = "http://www.latin-dictionary.net/search/english/" + orig_word.word
    r = try_fetch(base_url, headers={})
    if not r:
      print('no r')
    if r:
      page = r.content
      soup = BeautifulSoup(page, features="html.parser")
      entry = soup.findAll('div', { 'class': 'entry' })
      print(entry)
      for e in entry:
        translations = e.findAll('h3')
        print(translations)
        for t in translations:
          translations_for_db.append(t.get_text())
    for trans_for_db in translations_for_db:
      print(trans_for_db)
      w = Word.objects.filter(word=trans_for_db, language='latin').first()
      if not w:
        w = Word.objects.create(word=trans_for_db, lookup_date=timezone.now(), language='latin', from_translation=True) 
      w.translations.add(orig_word)
      trans_to_return.append(w)

    return trans_to_return

  def fetch_inflections(self, word):
    print('Fetching inflections for latin word')
    base_url = "https://la.wiktionary.org/wiki/" + word.word
    r = try_fetch(base_url, headers={})
    if not r:
      print('no r')
    if r:
      page = r.content
      soup = BeautifulSoup(page, features="html.parser")
      i = soup.find('table', { 'class': "inflection-table" })
      print('creating infls')
      i_db = Inflections.objects.create(inflections=str(i))
      word.inflections = i_db 
      word.did_inflections = 1 
      word.save(update_fields=['did_inflections', 'inflections'])
      print('i did the job')
      return i_db
      

  def fetch_word(self, word):
    print('Fetching latin word')
    definitions_map = {}
    definitions = []
    base_url = 'http://www.perseus.tufts.edu/hopper/morph?la=la&l=' + word
    r = try_fetch(base_url, headers={})
    originals = []
    infls_string = ''
    if not r:
      print('no r')
    if r:
      page = r.content
      soup = BeautifulSoup(page, features="html.parser")
      links = soup.findAll('a', id=lambda x: x and x.find('59') != -1 )
      lemmas = soup.findAll('div', {'class': 'lemma'} )
      if not lemmas:
        return ();
      for l in lemmas:
        print(l)
        inflections = l.findAll('td', {'class': '', 'style': ''}, lambda tag: tag.string is None)
        print(inflections)
        infls = [ i.string for i in inflections ]
        infls_string = infls_string + ','.join(infls) + ','
      for l in links:
        lsh = re.search('(Perseus:text:(2000|1999).04.0059.+?)\'', l['onclick'])
        if not lsh:
          continue
        lsh = lsh.group(1)
        original = lsh.split('=')[1].strip()
        print('original:', original, 'haha');
        try:
          o = Word.latin_objects.get(word=original)
          print(o.definition)
          definitions.append(o.definition)
        except:
          lsh_base_url = 'http://www.perseus.tufts.edu/hopper/loadquery?doc=' + lsh
          print('will fetch fresh');
          print(lsh_base_url)
          r = try_fetch(lsh_base_url, headers={})
          if not r:
            print('no r')
          if r:
            originals.append(original)
            page = r.content
            soup = BeautifulSoup(page, features="html.parser")
            page_definitions = soup.findAll('div', { 'class': 'lex_sense'})
            for d in page_definitions:

words/forms.py
from django import forms

class WordForm(forms.Form):
    word = forms.CharField(max_length=100)

words/templates/words/index.html
{% load static %}
<html>
    <head>
        <title>Dictionary App</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Keania+One|Libre+Baskerville" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/word.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="{% static 'js/jQuery.highlighter.js' %}"></script>
        <script src="{% static 'js/word.js' %}"></script>

    </head>
    <body>

<script type="text/javascript">
$(document).ready(init);


	function init() 
	{

$('.post').highlighter({
                           'selector': '.js-highlight',
                           'minWords': 0,
                           'complete': function (data) { 
                             $(".wd-lookup-link").prop("onclick", null).off("click"); 
                             $(".wd-lookup-link").click(function() { lookup_word(data); }); }
}
);
 $("#wd-look-up").click(function() { lookup_word($("#id_word").val() ); });
// $("#id_word").change(function() { lookup_word($(this).val() ); });
// $("#id_word").keyup(function() { if (e.keyCode == 13) { lookup_word($(this).val() ); } });
};



function lookup_word(word) {
    let all_words = $.map($(".word"), function(n) { return $(n).text(); });
    if (all_words.indexOf(word) != -1) {
      alert(`i already have the word ${word}`);
    }
    else { 
      $.ajax({
        type: "POST",
        url: "/words/", 
        data: {'word': word, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success : function(data) {
             $('.content').append(data);
$('.post').highlighter({
                           'selector': '.js-highlight',
                           'minWords': 0,
                           'complete': function (data) { $(".wd-lookup-link").prop("onclick", null).off("click"); $(".wd-lookup-link").click(function() { lookup_word(data); }); }
}
);
         }
});

    }
};

</script>

<div class="content container">
  <div class="row">
    <form action="/words/" method="post">
    {% csrf_token %}
    <div class="wd-form-cont">
      <div class="wd-lbl">New Word:</div><div class="wd-input">{{ form.word }} <button id="wd-look-up" type="button" class="btn btn-primary">Look Up</button></div>
    </div>
    </form>
  </div>
{% include "words/one_word.html" %}
  </div>
</div>

<div class="lookup-bar-highlight js-highlight yr-highlight" style="display:none">
<div class="yr-lookup"><a class="wd-lookup-link lookup-bar-highlight">Look Up</a>
</div>
</div>
</body>
</html>

words/templates/words/one_word.html
{% if word %}
  <div class="row">
<div> <h1 class="word"><a href="/">{{ word }}</a></h1> </div>
        <div class="col-md-8">
            <div class="wd-scr">
            {% for e in content %}
                <div class="post">
                    {% if e.etymology %}<p>{{ e.etymology }}</p>{% endif %}
                    {% for d in e.definitions %}
                      <div class="definition">
                      <p>{{ d.definition }}</p>
                      </div>
                      {% for e in d.examples %}
                      <li>{{ e.example }}</li>
                      {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        </div>
</div>
{% endif %}

words/templates/words/words.html
{% load static %}
<html>
    <head>
        <title>Dictionary App</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Keania+One|Libre+Baskerville" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Keania&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/word.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="{% static 'js/jQuery.highlighter.js' %}"></script>
        <script src="{% static 'js/word.js' %}"></script>

    </head>
    <body>

<script type="text/javascript">
$(document).ready(init);
	function init() 
	{
$('.post').highlighter({
                           'selector': '.js-highlight',
                           'minWords': 0,
                           'complete': function (data) {  }
}
);
}
</script>
<form action="/words/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Look Up" />
</form>

        <div>
            <h1><a href="/">{{ word }}</a></h1>
        </div>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            <div class="wd-scr">
            {% for e in content %}
                <div class="post">
<div class="lookup-bar-highlight js-highlight yr-highlight">
<div class="yr-lookup"><a class="lookup-bar-highlight">Look me up too</a>
</div>
</div>
                    {% if e.etymology %}<p>{{ e.etymology }}</p>{% endif %}
                    {% for d in e.definitions %}
                      <p>{{ d.definition }}</p>
                      {% for e in d.examples %}
                      <li>{{ e.example }}</li>
                      {% endfor %}
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
        </div>
    </div>
</div>

</body>
</html>